### ISSUE TITLE
Why can't I write `withInterface`?

### ISSUE THREAD

**Issue by i-am-tom** [purescript-node/purescript-node-readline#10]
Hello! Firstly, thank you for this package - it's wonderful. Secondly, I've hit a wall, and I *think* it's because of asynchronous impurities. I wanted to write this little function, `withInterface`, to tidy up some of my logic:

```purescript
withInterface :: forall a . (Interface -> Program a) -> Program a
withInterface f = do
  interface <- createConsoleInterface noCompletion
  result    <- f interface

  close interface
  pure result
```

The problem is that writing something like `withInterface $ \interface -> prompt interface` will show a prompt and immediately close it. Presumably, this is because `close interface` runs before I have time to type anything into the prompt. I'm pretty new to PureScript, but is this something that could be solved with the help of `Aff`?

Sorry, I think/hope I answered my own question, but I'm hoping I can work to build something to allow this :) Thanks!

**Comment by garyb** [comment]
You have indeed answered your own question; `Aff` is the asynchronous version of `Eff`. :)

If you were using `Aff` then `f` could await some response before returning the result, with no need to deal with explicit callbacks or anything like that.

**Comment by i-am-tom** [comment]
Well, I hope I haven't jumped the gun, but I've written a little module that puts the focus on `readline.question` - is this worthwhile? Or am I being far too eager? https://github.com/i-am-tom/purescript-node-readline-question

(Deliberately asking before publishing!)

**Comment by i-am-tom** [comment]
Following @paf31's [tweet](https://twitter.com/paf31/status/834475801047240704), I've published [the package](https://pursuit.purescript.org/packages/purescript-node-readline-question/0.2.1)! However, let me know if I'm missing some obvious way to recreate this behaviour and I'll remove it from Pursuit (assuming I can work out how!) - no point in me duplicating work :)

If, on the other hand, it _does_ have some use, I would love to talk about transforming it into a PR for this library? Sorry, this thread's title is probably not so applicable anymore!

**Comment by JordanMartinez** [comment]
Closing as there is an `Aff` variant of this now.
